services:
  web-api:
    build:
      target: dev
    volumes:
      - ./web-api:/app
      - web_api_venv:/app/.venv

  worker:
    build:
      target: dev
    volumes:
      - ./web-api:/app
      - worker_venv:/app/.venv

  web:
    build:
      target: dev
    ports: !override
      - "5173:5173"
    volumes:
      - ./web:/app
      - web_node_modules:/app/node_modules

volumes:
  web_api_venv:
  worker_venv:
  web_node_modules:
